[font]
size = 18

[[font.normal]]
family = "Liga SFMono Nerd Font"
style = "Light"

[[font.normal]]
family = "MonoLisa Nerd Font Mono"

[font.features]
"MonoLisa Nerd Font Mono" = [
  "+ss01",
  "+ss07",
  "+ss11",
  "-calt",
  "+ss09",
  "+ss02",
  "+ss14",
  "+ss16",
  "+ss17",
]
