[font]
normal = ["MonoLisa Nerd Font Mono", "Liga SFMono Nerd Font"]
size = 18
[font.features]
"MonoLisa Nerd Font Mono" = [
  "+ss01",
  "+ss07",
  "+ss11",
  "-calt",
  "+ss09",
  "+ss02",
  "+ss14",
  "+ss16",
  "+ss17",
]
